.TH "HTPDATE" "8" "version 1.3.0" "htpdate"
.SH "NAME"
htpdate \- Time synchronization (daemon)
.SH "SYNOPSIS"
.B htpdate
[\-046adhlnqstvxDF] [\-i pid file] [\-m minpoll] [\-M maxpoll] [\-p precision] [\-P <proxyserver>[:port]] [\-u user[:group]] <URL> ...
.SH "DESCRIPTION"
The HTTP Time Protocol (HTP) is used to synchronize a computer's time with web servers as reference time source. Htp will synchronize your computer's time using the Greenwich Mean Time (GMT) HTTP headers timestamp from web servers. HTTP and HTTPS are both supported.

The htpdate package includes a program for retrieving the date and time from remote machines via a network. Htpdate works through proxy servers. Accuracy of htpdate will be usually within 0.5 seconds (better with multiple servers). If this is not good enough for you, use a ntp package like ntpd, OpenNTPD or chrony.
.fi
.SH OPTIONS
.TP
.I \-0
HTTP/1.0 request (default is HTTP/1.1).
.TP
.I \-4
Force IPv4 name resolution only. Default behaviour is to try IPv6 first and fall back to IPv4.
.TP
.I \-6
Force IPv6 name resolution only.
.TP
.I \-a
Adjust time smoothly (default in daemon mode).
.TP
.I \-d
Turn debug on. Shows the "raw" timestamp, round trip time, time delta and and basic statistics of web server responses. Useful to determining the quality of a specific web server as time source. Multiple -d options increase verbosity. The maximum is 3.
.TP
.I \-h
Show help.
.TP
.I \-i
Set the pid file (default /var/run/htpdate.pid).
.TP
.I \-l
Use syslog for output (levels LOG_WARNING and LOG_INFO). Convenient if you use htpdate from cron.
.TP
.I \-m \-M
These options specify the minimum (\-m) and maximum (\-M) polling intervals for HTP requests, in seconds. The default range is between 30 minutes and 32 hours. Htpdate calculates the optimal polling frequency between minimum and maximum values. Only applicable when running in daemon mode.
.TP
.I \-n
Don't use a proxy, even if the appropriate http_proxy environment variable is defined.
.TP
.I \-p
Precision determines the operating accuracy of htpdate. Precision specifies the number of steps (default 4, maximum of 9) for htpdate to determine the second boundary.
.TP
.I \-q
Query web server and display time, but do not change time (default in interactive mode).
.TP
.I \-s
Set time immediate. In daemon mode \-s only applies the first poll.
.TP
.I \-t
Turn off sanity time check. By default a time offset larger than a year, compared to current localtime, is rejected. With \-t set, any time stamp will be accepted.
.TP
.I \-u
Set the user and group that the server normally runs at (default is root).
.TP
.I \-v
Show version.
.TP
.I \-x
Let htpdate compensate for the systematisch clock drift by adjusting system clock frequency.
.TP
.I \-D
Run as daemon. This option requires root privileges.
.TP
.I \-F
Run daemon in foreground. Daemon will not fork or write PID file. This option requires root privileges.
.TP
.I \-P
Proxy server hostname or IP address.
.TP
.I host
Web server hostname or IP address. Up to 16 hosts may be specified, but in general 3 to 5 hosts should be enough for a redundant and accurate setup.
.TP
.I port
Port number (default 80 and 8080 for proxy server).
.TP
.I path
Path to resource (e.g. /index.html).
.SH "ENVIRONMENT"
Htpdate supports proxies for HTTP connections. The standard way to specify the proxy location, which htpdate recognizes, is using the following environment variable:
.IP "\fBhttp_proxy\fR" 4
.IX Item "http_proxy"
.PD
If set, the http_proxy variable should contain the URL of the proxy for HTTP connections.
.SH "EXAMPLES"
Request time from web server (don't update local clock):
.br
\&    htpdate www.example.com
.P
Request time from multiple web servers:
.br
\&    htpdate www.example.com https://example.com http://example.com:80
.P
Debug output (don't update local clock):
.br
\&    htpdate \-d www.example.com
.br
Adjust time smoothly and log output to syslog (eg. cron):
.br
\&    htpdate \-al www.example.com:80/htpdate.html
.P
HTTP/1.0 request in IPv6 literal format (RFC 2732):
.br
\&    htpdate \-0 [2001:db8:1af6::123]:80
.P
Run htpdate as daemon:
.br
\&    htpdate \-D https://www.example.com
.P
Run htpdate in the foreground with all output going to the terminal:
.br
\&    htpdate \-F www.example.com
.P
Daemon mode for the security minded:
.br
\&    htpdate \-D \-u nobody:nogroup www.example.com
.SH "AUTHOR"
Eddy Vervest <eddy@vervest.org>, http://www.vervest.org/htp
.SH "SEE ALSO"
.BR rdate,
.BR timed,
.BR ntpd,
.BR OpenNTPD,
.BR chrony,
.BR adjtimex(8),
.BR ntp_adjtime,
